language: go

services:
  - docker

addons:
  sonarcloud:
    organization: "svenjeppsson-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN

before_install:
  - ./start-db-container.sh $DB_PORT $DB_CONTAINER $DB_PASSWORD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull xthinker/go-builder:$GO_BUILDER_VERSION
  - ./waitForContainer.sh $DB_CONTAINER

script:
  - docker run -ti --link $DB_CONTAINER:mysql -e "DBCON=$DB_USER:$DB_PASSWORD@tcp(mysql:3306)/TEST" -v $(pwd):/go/src/app xthinker/go-builder:$GO_BUILDER_VERSION

after_success:
  - sonar-scanner
