language: go

services:
  - docker

addons:
  sonarcloud:
    organization: "svenjeppsson-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN

before_install:
  - ./start-db-container.sh 3307 testdb secret

script:
  - docker run -ti --link testdb:mysql -e "DBCON=root:secret@tcp(mysql:3307)/TEST" -v $(pwd):/go/src/app xthinker/go-builder:0.0.3

after_success:
  - sonar-scanner
