language: go
go:
  - 1.11.5

services:
  - docker
  - mysql

addons:
  sonarcloud:
    organization: "svenjeppsson-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN
env:
  global:
    - GO111MODULE=on
    - DBCON="root@tcp(localhost:3306)/TEST"

before_install:
  - mysql < schema.sql
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - dep ensure

script:
  - golangci-lint run
  - go vet .
  - go test -v ./... -run ^TestIntegration.* -coverprofile=cov.out
  - go test -v ./... -run ^TestUnit.* -coverprofile=cov.out


after_success:
  - sonar-scanner
