language: go
go:
  - 1.11.5

services:
  - docker
  - mysql

env:
  global:
    - DBCON="root@tcp(localhost:3306)/TEST"

before_install:
  - mysql < schema.sql

after_success:
  - docker run --rm --mount type=volume,src="$(pwd)",dst=/opt/app,type=bind -w=/opt/app red6/docker-sonar-scanner:latest sonar-scanner -Dsonar.login=$SONAR_TOKEN

after_script:
  - docker stop testdb