language: go

services:
  - docker

env:
  - GO_BUILDER_VERSION=0.0.3
addons:
  sonarcloud:
    organization: "svenjeppsson-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN

before_install:
  - ./start-db-container.sh 3307 testdb secret
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull xthinker/go-builder:$GO_BUILDER_VERSION
  - ./waitForContainer.sh testdb

script:
  - docker run -ti --link testdb:mysql -e "DBCON=root:secret@tcp(mysql:3307)/TEST" -v $(pwd):/go/src/app xthinker/go-builder:$GO_BUILDER_VERSION

after_success:
  - sonar-scanner
