language: bash

services:
  - docker

addons:
  sonarcloud:
    organization: "svenjeppsson-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN
env:
  global:
    - GO111MODULE=on
    - DBPORT=3306

before_install:
  - ./start-db-container.sh 3306 testdb secret

script:
  - docker run -ti --link testdb:mysql -e "DBCON=root:secret@tcp(mysql:3306)/TEST" -v $(pwd):/go/src/app xthinker/go-builder:latest

after_success:
  - sonar-scanner
