language: go
go:
  - 1.11.5

services:
  - docker
  - mysql

addons:
  sonarcloud:
    organization: "svenjeppsson-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN
env:
  global:
    - DBCON="root@tcp(localhost:3306)/TEST"

before_install:
  - mysql < schema.sql

after_success:
  - sonar-scanner

after_script:
  - docker stop testdb