CREATE DATABASE if not exists TEST;
USE TEST;
CREATE TABLE if not exists PERSON
(
  ID        INTEGER AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255),
  LASTNAME  VARCHAR(255),
  PRIMARY KEY (ID),
  UNIQUE KEY (FIRSTNAME, LASTNAME)
) COMMENT ='this is my test table';

